<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spt_typo3audit"
 *
 * Auto generated by Extension Builder 2019-09-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 Audit',
    'description' => 'Extension can be used to analyse a complete TYPO3 website system overview and it can be used to understand the server details and the extensions installed and their compatibility which are installed in the system. It is also possible to save this report as a PDF file.',
    'category' => 'module',
    'module' => '',
    'author' => 'Arun Chandran',
    'author_email' => 'arun@spawoz.com',
    'author_company' => 'Spawoz Technologies',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
